/*Fila 1 asiento 9 Hector Rolando Rivera Varela
 */
package examen5p2_hectorrivera;

import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hriverav
 */
public class Examen5P2_HectorRivera extends javax.swing.JFrame {
    
    /**
     * Creates new form examen5P2_HectorRivera
     */
    public Examen5P2_HectorRivera() {
        initComponents();
        usuarios.add(new empleados("ing.sistemas","IT",8,"j","n","2","Female","Comayagua","",new Date(95, 12, 1)));
        usuarios.get(0).setNumID(ID(usuarios.getLast()));
        usuarios.add(new Civilies("jaf","algo","121xc","Male","Francisco Morazan","",new Date(104, 3, 12)));
        usuarios.get(1).setNumID(ID(usuarios.getLast()));
        usuarios.add(new Civilies("q","a","1","Male","Cortés","",new Date(104, 4, 12)));
        usuarios.get(2).setNumID(ID(usuarios.getLast()));
        
        DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox_Choose.getModel();
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i) instanceof Civilies) {
                model.addElement(usuarios.get(i));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_Civiles = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel_GreetingCivil = new javax.swing.JLabel();
        jButton_CerrarSesionCivil = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Civil_Info = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Civil_tramites = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_descripcion = new javax.swing.JTextArea();
        jTextField_tramiteNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton_saveTramite = new javax.swing.JButton();
        jFrame_Empleados = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel_GreetingEMP = new javax.swing.JLabel();
        jButton_CerrarSesionEMP = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Tramites = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Civiles = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jComboBox_Choose = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField_new_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_new_Apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_sex = new javax.swing.JComboBox<>();
        jComboBox_dept = new javax.swing.JComboBox<>();
        jPasswordField_new_password = new javax.swing.JPasswordField();
        jCalendar_new_Date = new com.toedter.calendar.JCalendar();
        jLabel9 = new javax.swing.JLabel();
        jButton_modificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jPasswordField_contraseña = new javax.swing.JPasswordField();
        jButton_IgresarLogin = new javax.swing.JButton();

        jFrame_Civiles.setMinimumSize(new java.awt.Dimension(506, 614));
        jFrame_Civiles.setPreferredSize(new java.awt.Dimension(506, 571));
        jFrame_Civiles.setResizable(false);
        jFrame_Civiles.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(506, 614));

        jLabel_GreetingCivil.setForeground(new java.awt.Color(0, 0, 0));

        jButton_CerrarSesionCivil.setText("Cerrar Sesion");
        jButton_CerrarSesionCivil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CerrarSesionCivilMouseClicked(evt);
            }
        });

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jTable_Civil_Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre completo", "No.identidad", "fecha de nacimiento"
            }
        ));
        jScrollPane3.setViewportView(jTable_Civil_Info);

        jTable_Civil_tramites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre tramite", "descripcion", "fecha", "No.identidad"
            }
        ));
        jScrollPane4.setViewportView(jTable_Civil_tramites);

        jLabel12.setText("Tramites");

        jLabel13.setText("informacion personal");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Infromacion personal", jPanel4);

        jTextArea_descripcion.setColumns(20);
        jTextArea_descripcion.setRows(5);
        jScrollPane5.setViewportView(jTextArea_descripcion);

        jLabel14.setText("Nombre:");

        jLabel15.setText("descripcion:");

        jButton_saveTramite.setText("creat");
        jButton_saveTramite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_saveTramiteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addComponent(jTextField_tramiteNombre)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(jLabel14))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(jLabel15))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(jButton_saveTramite)))
                        .addGap(0, 212, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_tramiteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_saveTramite)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestion de tramites", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel_GreetingCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_CerrarSesionCivil)
                .addGap(39, 39, 39))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_GreetingCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CerrarSesionCivil))
                .addGap(74, 74, 74)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jFrame_Civiles.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jFrame_Empleados.setFocusable(false);
        jFrame_Empleados.setPreferredSize(new java.awt.Dimension(506, 614));
        jFrame_Empleados.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(506, 614));

        jLabel_GreetingEMP.setForeground(new java.awt.Color(0, 0, 0));

        jButton_CerrarSesionEMP.setText("Cerrar Sesion");
        jButton_CerrarSesionEMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CerrarSesionEMPMouseClicked(evt);
            }
        });

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jTable_Tramites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre tramite", "descripcion", "fecha ", "No.Identidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Tramites);

        jTable_Civiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Completo", "No.Identidad", "fecha Nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_Civiles);

        jLabel10.setText("Tramites");

        jLabel11.setText("informacion civiles");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        jTabbedPane2.addTab("Infroamcion Civiles", jPanel5);

        jComboBox_Choose.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ChooseItemStateChanged(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("contraseña");

        jTextField_new_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_new_ApellidoActionPerformed(evt);
            }
        });

        jLabel6.setText("apellido");

        jLabel7.setText("sexo");

        jLabel8.setText("departamento");

        jComboBox_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));

        jComboBox_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comayagua", "Cortés", "Francisco Morazan" }));

        jLabel9.setText("Fecha nacimiento");

        jButton_modificar.setText("Modificar");
        jButton_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_modificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jPasswordField_new_password))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(jCalendar_new_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButton_modificar))
                                            .addComponent(jTextField_new_Name))
                                        .addGap(62, 62, 62)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField_new_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox_Choose, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(127, 127, 127))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_Choose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_new_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_new_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPasswordField_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCalendar_new_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton_modificar)
                .addGap(75, 75, 75))
        );

        jTabbedPane2.addTab("Modificar Civilies", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel_GreetingEMP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_CerrarSesionEMP)
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_GreetingEMP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CerrarSesionEMP))
                .addGap(69, 69, 69)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jFrame_Empleados.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre completo:");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");

        jButton_IgresarLogin.setText("Ingresar");
        jButton_IgresarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_IgresarLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(jPasswordField_contraseña)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton_IgresarLogin)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_IgresarLogin)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IgresarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_IgresarLoginMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < usuarios.size(); i++) {
            if (jTextField_nombre.getText().equals(usuarios.get(i).getNombre()+" "+usuarios.get(i).getApellido())) {
                if (jPasswordField_contraseña.getText().equals(usuarios.get(i).getContraseña())) {
                    this.setVisible(false);
                    
                    if (usuarios.get(i) instanceof Civilies) {
                        jLabel_GreetingCivil.setText("Bienvenido: "+ usuarios.get(i).getNombre()+" "+usuarios.get(i).getApellido());
                        jFrame_Civiles.setVisible(true);
                        jFrame_Empleados.pack();
                        
                    }else if(usuarios.get(i) instanceof empleados){
                        jLabel_GreetingEMP.setText("Bienvenido: "+ usuarios.get(i).getNombre()+" "+usuarios.get(i).getApellido());
                        jFrame_Empleados.setVisible(true);
                        jFrame_Empleados.pack();
                    }
                    
                }
            }
        }
        
        
    }//GEN-LAST:event_jButton_IgresarLoginMouseClicked

    private void jButton_CerrarSesionEMPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CerrarSesionEMPMouseClicked
        // TODO add your handling code here:
        jTextField_nombre.setText("");
        jPasswordField_contraseña.setText("");
        jFrame_Empleados.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton_CerrarSesionEMPMouseClicked

    private void jButton_CerrarSesionCivilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CerrarSesionCivilMouseClicked
        // TODO add your handling code here:
        jTextField_nombre.setText("");
        jPasswordField_contraseña.setText("");
        jFrame_Civiles.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton_CerrarSesionCivilMouseClicked

    private void jComboBox_ChooseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ChooseItemStateChanged
        // TODO add your handling code here:
        int pos = jComboBox_Choose.getSelectedIndex()+1;
        jTextField_new_Name.setText(usuarios.get(pos).getNombre());
        jTextField_new_Apellido.setText(usuarios.get(pos).getApellido());
        jPasswordField_new_password.setText(usuarios.get(pos).getContraseña());
        if (usuarios.get(pos).getSexo().equals("Female")) {
            jComboBox_sex.setSelectedIndex(0);
        }else if(usuarios.get(pos).getSexo().equals("Male")){
            jComboBox_sex.setSelectedIndex(1);
        }
        if (usuarios.get(pos).getSexo().equals("Comayagua")) {
            jComboBox_sex.setSelectedIndex(0);
        }else if(usuarios.get(pos).getSexo().equals("Cortés")){
            jComboBox_sex.setSelectedIndex(1);
        }else if(usuarios.get(pos).getSexo().equals("Francisco Morazan")){
            jComboBox_sex.setSelectedIndex(2);
        }
        jCalendar_new_Date.setDate(usuarios.get(pos).getFN());
        
    }//GEN-LAST:event_jComboBox_ChooseItemStateChanged

    private void jTextField_new_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_new_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_new_ApellidoActionPerformed

    private void jButton_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_modificarMouseClicked
        // TODO add your handling code here:
        int pos = jComboBox_Choose.getSelectedIndex()+1;
        usuarios.get(pos).setNombre(jTextField_new_Name.getText());
        usuarios.get(pos).setApellido(jTextField_new_Apellido.getText());
        usuarios.get(pos).setContraseña(jPasswordField_contraseña.getText());
        
        usuarios.get(pos).setDepartamento((String)jComboBox_dept.getSelectedItem());
        usuarios.get(pos).setSexo((String)jComboBox_sex.getSelectedItem());
        usuarios.get(pos).setFN(jCalendar_new_Date.getDate());
        
        
        
    }//GEN-LAST:event_jButton_modificarMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) jTable_Civil_Info.getModel();
        DefaultTableModel model2 = (DefaultTableModel) jTable_Civil_tramites.getModel();
        Civilies u = (Civilies)usuarios.get(usuario);
            
        Object arg1[] = {u.getNombre()+" "+u.getApellido(),u.getNumID(),u.getFN()};
        model1.addRow(arg1);
        for (tramite t : u.getTramites()) {
            Object arg2[] = {t.getNombre(),t.getID_usada(),t.getFechaEnviada(),u.getNumID()};
            model2.addRow(arg2);
        }   
                      
        

        jTable_Civiles.setModel(model1);
        jTable_Tramites.setModel(model2);
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) jTable_Civiles.getModel();
                    DefaultTableModel model2 = (DefaultTableModel) jTable_Tramites.getModel();
                    for (Usuario u : usuarios) {
                        if (u instanceof Civilies) {
                            Object arg1[] = {u.getNombre()+" "+u.getApellido(),u.getNumID(),u.getFN()};
                            model1.addRow(arg1);
                            for (tramite t : ((Civilies)u).getTramites()) {
                                Object arg2[] = {t.getNombre(),t.getID_usada(),t.getFechaEnviada(),u.getNumID()};
                                model2.addRow(arg2);
                            }   
                        }            
                    }
        
                    jTable_Civiles.setModel(model1);
                    jTable_Tramites.setModel(model2);
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jButton_saveTramiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_saveTramiteMouseClicked
        // TODO add your handling code here:
        ((Civilies)usuarios.get(usuario)).getTramites().add(
                new tramite(jTextField_nombre.getText(), usuarios.get(usuario).getNumID(), new Date()));
    }//GEN-LAST:event_jButton_saveTramiteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen5P2_HectorRivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen5P2_HectorRivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen5P2_HectorRivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen5P2_HectorRivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen5P2_HectorRivera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CerrarSesionCivil;
    private javax.swing.JButton jButton_CerrarSesionEMP;
    private javax.swing.JButton jButton_IgresarLogin;
    private javax.swing.JButton jButton_modificar;
    private javax.swing.JButton jButton_saveTramite;
    private com.toedter.calendar.JCalendar jCalendar_new_Date;
    private javax.swing.JComboBox<String> jComboBox_Choose;
    private javax.swing.JComboBox<String> jComboBox_dept;
    private javax.swing.JComboBox<String> jComboBox_sex;
    private javax.swing.JFrame jFrame_Civiles;
    private javax.swing.JFrame jFrame_Empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_GreetingCivil;
    private javax.swing.JLabel jLabel_GreetingEMP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField_contraseña;
    private javax.swing.JPasswordField jPasswordField_new_password;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable_Civil_Info;
    private javax.swing.JTable jTable_Civil_tramites;
    private javax.swing.JTable jTable_Civiles;
    private javax.swing.JTable jTable_Tramites;
    private javax.swing.JTextArea jTextArea_descripcion;
    private javax.swing.JTextField jTextField_new_Apellido;
    private javax.swing.JTextField jTextField_new_Name;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_tramiteNombre;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Usuario> usuarios = new ArrayList<>();
    private int usuario=0;
    
    public String ID(Usuario usuario){
        String ID ="";
        Random rd = new Random();
        int aux = 0;
        
        if (usuario.getDepartamento().equals("Francisco Morazan")) {
            ID= ID+"01";
            aux = rd.nextInt(28)+1;
            if (aux<10) {
                ID= ID+0+""+aux;
            }else{
                ID= ID+""+aux;
            }
        }else if(usuario.getDepartamento().equals("Cortés")){
            ID= ID+"02";
            aux = rd.nextInt(12)+1;
            if (aux<10) {
                ID= ID+0+""+aux;
            }else{
                ID= ID+""+aux;
            }
        }else if(usuario.getDepartamento().equals("Comayagua")){
            ID= ID+"03";
            aux = rd.nextInt(21)+1;
            if (aux<10) {
                ID= ID+0+""+aux;
            }else{
                ID= ID+""+aux;
            }
        }
        
        ID= ID + "-"+usuario.getFN().getYear()+"-";
        
        for (int i = 0; i < 5; i++) {
            ID = ID + rd.nextInt(10);
        }
        return ID;
    }
}
